services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=root
    #   - DB_PASSWORD=password
    #   - DB_NAME=fifa_db
    # depends_on:
    #   - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '4200:4200'
  #   depends_on:
  #     - backend

  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: fifa_db
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - db_data:/var/lib/mysql

volumes:
  - .:/app
