#docker-compose
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["npx", "nodemon", "--legacy-watch", "src/app.ts"]

