services:

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 'fifa_db'
    ports:
      - "3307:3306"
    volumes:
      - ./database:/app
      
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - db


volumes:
  db_data:
